In [1]:
import Generate as gen

In [2]:
from Transformations import *

In [3]:
import numpy as np
import pandas as pd

In [4]:
s = gen.System(1000)

In [5]:
s.add_planet(x=[20.,30.],v=[0.4,-0.6])
s.add_planet(x=[10.,20.],v=[0.2,-0.7])

New planet
New planet


position    t
0       [10.1995527864, 19.2991055728, 0.0]    0
1       [10.3986152575, 18.5972833945, 0.0]    1
2       [10.5971402319, 17.8944999363, 0.0]    2
3       [10.7950761446, 17.1907217793, 0.0]    3
4       [10.9923667546, 16.4859160037, 0.0]    4
5       [11.1889508735, 15.7800506608, 0.0]    5
6       [11.3847621354, 15.0730953389, 0.0]    6
7       [11.5797288255, 14.3650218283, 0.0]    7
8       [11.7737737936, 13.6558048923, 0.0]    8
9        [11.966814482, 12.9454231431, 0.0]    9
10      [12.1587630994, 12.2338600166, 0.0]   10
11      [12.3495269777, 11.5211048338, 0.0]   11
12       [12.539009147, 10.8071539206, 0.0]   12
13      [12.7271091615, 10.0920117522, 0.0]   13
14      [12.9137242035, 9.37569206894, 0.0]   14
15      [13.0987504783, 8.65821890031, 0.0]   15
16      [13.2820848968, 7.93962742185, 0.0]   16
17      [13.4636270182, 7.21996456253, 0.0]   17
18      [13.6432811971, 6.49928928073, 0.0]   18
19       [13.820958852, 5.77767243655, 0.0]   19
20      [13.9965807455, 5.05519620795, 0.0]   20
21      [14.1700791445, 4.33195302911, 0.0]   21
22       [14.341399726, 3.60804406691, 0.0]   22
23      [14.5105030965, 2.88357729337, 0.0]   23
24      [14.6773658173, 2.15866525019, 0.0]   24
25       [14.841980867, 1.43342263207, 0.0]   25
26     [15.0043575146, 0.707963831464, 0.0]   26
27   [15.1645206267, -0.0175994123399, 0.0]   27
28    [15.3225094774, -0.743160132772, 0.0]   28
29      [15.478376161, -1.46861792555, 0.0]   29
..                                      ...  ...
970    [124.440944773, -652.488160604, 0.0]  970
971    [124.555420295, -653.176791847, 0.0]  971
972     [124.669895605, -653.86542198, 0.0]  972
973    [124.784370703, -654.554051005, 0.0]  973
974    [124.898845591, -655.242678923, 0.0]  974
975    [125.013320268, -655.931305738, 0.0]  975
976    [125.127794735, -656.619931451, 0.0]  976
977    [125.242268993, -657.308556065, 0.0]  977
978    [125.356743042, -657.997179581, 0.0]  978
979    [125.471216882, -658.685802003, 0.0]  979
980    [125.585690514, -659.374423333, 0.0]  980
981    [125.700163939, -660.063043572, 0.0]  981
982    [125.814637156, -660.751662724, 0.0]  982
983    [125.929110167, -661.440280789, 0.0]  983
984    [126.043582971, -662.128897772, 0.0]  984
985     [126.15805557, -662.817513673, 0.0]  985
986    [126.272527963, -663.506128495, 0.0]  986
987    [126.387000151, -664.194742241, 0.0]  987
988    [126.501472135, -664.883354912, 0.0]  988
989    [126.615943914, -665.571966511, 0.0]  989
990     [126.730415491, -666.26057704, 0.0]  990
991      [126.844886864, -666.9491865, 0.0]  991
992    [126.959358034, -667.637794895, 0.0]  992
993    [127.073829002, -668.326402227, 0.0]  993
994    [127.188299769, -669.015008497, 0.0]  994
995    [127.302770334, -669.703613708, 0.0]  995
996    [127.417240698, -670.392217862, 0.0]  996
997    [127.531710861, -671.080820961, 0.0]  997
998    [127.646180825, -671.769423008, 0.0]  998
999    [127.760650589, -672.458024004, 0.0]  999

[1000 rows x 2 columns]

In [6]:
pos0 = s.planets[0].history['position'].values
pos1 = s.planets[1].history['position'].values

In [7]:
pos1

array([array([ 10.19955279,  19.29910557,   0.        ]),
       array([ 10.39861526,  18.59728339,   0.        ]),
       array([ 10.59714023,  17.89449994,   0.        ]),
       array([ 10.79507614,  17.19072178,   0.        ]),
       array([ 10.99236675,  16.485916  ,   0.        ]),
       array([ 11.18895087,  15.78005066,   0.        ]),
       array([ 11.38476214,  15.07309534,   0.        ]),
       array([ 11.57972883,  14.36502183,   0.        ]),
       array([ 11.77377379,  13.65580489,   0.        ]),
       array([ 11.96681448,  12.94542314,   0.        ]),
       array([ 12.1587631 ,  12.23386002,   0.        ]),
       array([ 12.34952698,  11.52110483,   0.        ]),
       array([ 12.53900915,  10.80715392,   0.        ]),
       array([ 12.72710916,  10.09201175,   0.        ]),
       array([ 12.9137242 ,   9.37569207,   0.        ]),
       array([ 13.09875048,   8.6582189 ,   0.        ]),
       array([ 13.2820849 ,   7.93962742,   0.        ]),
       array([

In [8]:
pos_rel = pos1 - pos0

In [9]:
pos_cyl = cylindrical(pos_rel)

In [10]:
phis = pos_cyl[:,1]

In [11]:
phis /= np.pi

In [12]:
n = 3
series = make_time_series(phis, depth=n+1)
y = series[:,n]
x = series[:,0:n]

In [13]:
from keras.layers import Input, Dense
from keras.models import Model

Using TensorFlow backend.


In [18]:
inputs = Input(shape=(n,), dtype='float', name='main_input')
layer = Dense(60, activation='relu', kernel_initializer='normal')(inputs)
layer = Dense(15, activation='relu', kernel_initializer='normal')(layer)
predictions = Dense(1, kernel_initializer='normal')(layer)
model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer='adam',
              loss='mean_squared_error')

In [19]:
model.fit(x, y)

Epoch 1/1
996/996 [==============================] - 0s - loss: 0.6944     


In [20]:
x[0]

array([-0.75156261, -0.75307415, -0.75453663])

In [21]:
model.predict(x)

array([[-0.07848722],
       [-0.07854991],
       [-0.07861056],
       [-0.07866929],
       [-0.07872616],
       [-0.07878125],
       [-0.07883464],
       [-0.07888643],
       [-0.07893667],
       [-0.07898546],
       [-0.07903288],
       [-0.07907902],
       [-0.07912396],
       [-0.0791678 ],
       [-0.07921061],
       [-0.0792525 ],
       [-0.07929355],
       [-0.07933386],
       [-0.07937352],
       [-0.07941262],
       [-0.07945123],
       [-0.07948945],
       [-0.07952735],
       [-0.07956497],
       [-0.07960241],
       [-0.07963967],
       [-0.07967684],
       [-0.0797139 ],
       [-0.07975091],
       [-0.07978785],
       [-0.07982475],
       [-0.0798616 ],
       [-0.07989838],
       [-0.0799351 ],
       [-0.07997172],
       [-0.08000825],
       [-0.08004464],
       [-0.0800809 ],
       [-0.08011699],
       [-0.08015288],
       [-0.08018857],
       [-0.08022404],
       [-0.08025925],
       [-0.08029419],
       [-0.08032887],
       [-0