In [1]:
import Generate as gen

In [2]:
import ConvertTimeSeries as conv

In [3]:
import numpy as np
import pandas as pd

In [4]:
s = gen.System()

In [5]:
data = s.generate(x=[20.,30.],v=[0.4,-0.6])

New planet
            position   t
0  [20.0, 30.0, 0.0]  22


In [6]:
astr = conv.AstroData()

In [7]:
x = data['position']

In [8]:
data = astr.convert(data)

In [9]:
data

t-0  \
3    [21.5977734445, 27.5967939812, 0.0]   
4    [21.9966131706, 26.9951901964, 0.0]   
5    [22.3951924288, 26.3932667542, 0.0]   
6    [22.7935016903, 25.7910251144, 0.0]   
7    [23.1915314676, 25.1884672362, 0.0]   
8    [23.5892723514, 24.5855955888, 0.0]   
9    [23.9867150477, 23.9824131597, 0.0]   
10    [24.3838504173, 23.378923459, 0.0]   
11    [24.7806695153, 22.775130521, 0.0]   
12   [25.1771636306, 22.1710389018, 0.0]   
13   [25.5733243268, 21.5666536733, 0.0]   
14    [25.9691434804, 20.961980413, 0.0]   
15   [26.3646133198, 20.3570251905, 0.0]   
16    [26.759726462, 19.7517945498, 0.0]   
17   [27.1544759476, 19.1462954882, 0.0]   
18    [27.548855273, 18.5405354311, 0.0]   
19   [27.9428584209, 17.9345222044, 0.0]   
20    [28.3364798864, 17.328264003, 0.0]   
21   [28.7297147002, 16.7217693572, 0.0]   
22   [29.1225584484, 16.1150470966, 0.0]   
23   [29.5150072877, 15.5081063121, 0.0]   
24   [29.9070579573, 14.9009563168, 0.0]   
25   [30.2987077852, 14.2936066053, 0.0]   
26   [30.6899546924, 13.6860668134, 0.0]   
27   [31.0807971908, 13.0783466769, 0.0]   
28    [31.471234379, 12.4704559918, 0.0]   
29   [31.8612659328, 11.8624045744, 0.0]   
30   [32.2508920929, 11.2542022231, 0.0]   
31   [32.6401136493, 10.6458586821, 0.0]   
32   [33.0289319222, 10.0373836067, 0.0]   
..                                   ...   
70  [47.5498255923, -13.1105781677, 0.0]   
71  [47.9267490875, -13.7192383381, 0.0]   
72  [48.3034791595, -14.3278431403, 0.0]   
73  [48.6800203979, -14.9363919304, 0.0]   
74  [49.0563772805, -15.5448841549, 0.0]   
75  [49.4325541738, -16.1533193449, 0.0]   
76    [49.8085553352, -16.76169711, 0.0]   
77  [50.1843849134, -17.3700171336, 0.0]   
78  [50.5600469507, -17.9782791672, 0.0]   
79  [50.9355453841, -18.5864830261, 0.0]   
80  [51.3108840476, -19.1946285847, 0.0]   
81   [51.6860666738, -19.802715772, 0.0]   
82  [52.0610968962, -20.4107445682, 0.0]   
83  [52.4359782508, -21.0187150003, 0.0]   
84  [52.8107141787, -21.6266271387, 0.0]   
85  [53.1853080279, -22.2344810942, 0.0]   
86  [53.5597630557, -22.8422770144, 0.0]   
87  [53.9340824307, -23.4500150812, 0.0]   
88   [54.308269235, -24.0576955075, 0.0]   
89  [54.6823264667, -24.6653185352, 0.0]   
90  [55.0562570416, -25.2728844324, 0.0]   
91  [55.4300637957, -25.8803934912, 0.0]   
92  [55.8037494873, -26.4878460257, 0.0]   
93  [56.1773167989, -27.0952423699, 0.0]   
94  [56.5507683396, -27.7025828759, 0.0]   
95   [56.924106647, -28.3098679121, 0.0]   
96  [57.2973341892, -28.9170978619, 0.0]   
97  [57.6704533666, -29.5242731216, 0.0]   
98  [58.0434665144, -30.1313940997, 0.0]   
99   [58.4163759039, -30.738461215, 0.0]   

                                     t-1                                   t-2  
3    [21.1986827862, 28.1980771346, 0.0]    [20.799350705, 28.7990391519, 0.0]  
4    [21.5977734445, 27.5967939812, 0.0]   [21.1986827862, 28.1980771346, 0.0]  
5    [21.9966131706, 26.9951901964, 0.0]   [21.5977734445, 27.5967939812, 0.0]  
6    [22.3951924288, 26.3932667542, 0.0]   [21.9966131706, 26.9951901964, 0.0]  
7    [22.7935016903, 25.7910251144, 0.0]   [22.3951924288, 26.3932667542, 0.0]  
8    [23.1915314676, 25.1884672362, 0.0]   [22.7935016903, 25.7910251144, 0.0]  
9    [23.5892723514, 24.5855955888, 0.0]   [23.1915314676, 25.1884672362, 0.0]  
10   [23.9867150477, 23.9824131597, 0.0]   [23.5892723514, 24.5855955888, 0.0]  
11    [24.3838504173, 23.378923459, 0.0]   [23.9867150477, 23.9824131597, 0.0]  
12    [24.7806695153, 22.775130521, 0.0]    [24.3838504173, 23.378923459, 0.0]  
13   [25.1771636306, 22.1710389018, 0.0]    [24.7806695153, 22.775130521, 0.0]  
14   [25.5733243268, 21.5666536733, 0.0]   [25.1771636306, 22.1710389018, 0.0]  
15    [25.9691434804, 20.961980413, 0.0]   [25.5733243268, 21.5666536733, 0.0]  
16   [26.3646133198, 20.3570251905, 0.0]    [25.9691434804, 20.961980413, 0.0]  
17    [26.759726462, 19.7517945498, 0.0]   [26.3646133198, 20.3570251905, 0.0]  
18   [27.154

In [10]:
data.values

array([[array([ 21.59777344,  27.59679398,   0.        ]),
        array([ 21.19868279,  28.19807713,   0.        ]),
        array([ 20.79935071,  28.79903915,   0.        ])],
       [array([ 21.99661317,  26.9951902 ,   0.        ]),
        array([ 21.59777344,  27.59679398,   0.        ]),
        array([ 21.19868279,  28.19807713,   0.        ])],
       [array([ 22.39519243,  26.39326675,   0.        ]),
        array([ 21.99661317,  26.9951902 ,   0.        ]),
        array([ 21.59777344,  27.59679398,   0.        ])],
       [array([ 22.79350169,  25.79102511,   0.        ]),
        array([ 22.39519243,  26.39326675,   0.        ]),
        array([ 21.99661317,  26.9951902 ,   0.        ])],
       [array([ 23.19153147,  25.18846724,   0.        ]),
        array([ 22.79350169,  25.79102511,   0.        ]),
        array([ 22.39519243,  26.39326675,   0.        ])],
       [array([ 23.58927235,  24.58559559,   0.        ]),
        array([ 23.19153147,  25.18846724,   0.    

In [10]:
depth = 2
n = len(x) - depth

In [52]:
data = np.array(np.array(np.array([])))

In [56]:
data

array([], dtype=float64)

In [54]:
data[:,0]

IndexError: too many indices for array

In [55]:
x[0:n]

array([array([ 20.39978665,  29.39967998,   0.        ]),
       array([ 20.79935071,  28.79903915,   0.        ]),
       array([ 21.19868279,  28.19807713,   0.        ]),
       array([ 21.59777344,  27.59679398,   0.        ]),
       array([ 21.99661317,  26.9951902 ,   0.        ]),
       array([ 22.39519243,  26.39326675,   0.        ]),
       array([ 22.79350169,  25.79102511,   0.        ]),
       array([ 23.19153147,  25.18846724,   0.        ]),
       array([ 23.58927235,  24.58559559,   0.        ]),
       array([ 23.98671505,  23.98241316,   0.        ]),
       array([ 24.38385042,  23.37892346,   0.        ]),
       array([ 24.78066952,  22.77513052,   0.        ]),
       array([ 25.17716363,  22.1710389 ,   0.        ]),
       array([ 25.57332433,  21.56665367,   0.        ]),
       array([ 25.96914348,  20.96198041,   0.        ]),
       array([ 26.36461332,  20.35702519,   0.        ]),
       array([ 26.75972646,  19.75179455,   0.        ]),
       array([

In [38]:
data = np.append(data, x[0:n], axis=1)

ValueError: all the input arrays must have same number of dimensions

In [30]:
len(x[0:n])

98

In [15]:
for i in range(0, depth):
    data = np.append(data, x[i:n - i], axis=1)

ValueError: all the input arrays must have same number of dimensions

NameError: name 'np' is not defined

In [24]:
data = np.append(data, x, axis=1)

IndexError: axis 1 out of bounds [0, 1)

In [25]:
data

array([array([ 20.39978665,  29.39967998,   0.        ]),
       array([ 20.79935071,  28.79903915,   0.        ]),
       array([ 21.19868279,  28.19807713,   0.        ]),
       array([ 21.59777344,  27.59679398,   0.        ]),
       array([ 21.99661317,  26.9951902 ,   0.        ]),
       array([ 22.39519243,  26.39326675,   0.        ]),
       array([ 22.79350169,  25.79102511,   0.        ]),
       array([ 23.19153147,  25.18846724,   0.        ]),
       array([ 23.58927235,  24.58559559,   0.        ]),
       array([ 23.98671505,  23.98241316,   0.        ]),
       array([ 24.38385042,  23.37892346,   0.        ]),
       array([ 24.78066952,  22.77513052,   0.        ]),
       array([ 25.17716363,  22.1710389 ,   0.        ]),
       array([ 25.57332433,  21.56665367,   0.        ]),
       array([ 25.96914348,  20.96198041,   0.        ]),
       array([ 26.36461332,  20.35702519,   0.        ]),
       array([ 26.75972646,  19.75179455,   0.        ]),
       array([

In [11]:
astr.convert(x)

IndexError: axis 1 out of bounds [0, 1)

In [9]:
orbit=orb

In [10]:
depth=5

In [11]:
timedata=orbit.drop("t",axis=1)
for i in range(0,depth):
#            newcolumn=timedata[i+1:len(timedata)-self.depth+i].reset_index()["x"]                      

    newcolumn=timedata[i+1:]
    newcolumn=newcolumn.reset_index()["position"]


    timedata = pd.concat([timedata.copy(),newcolumn.copy()],axis=1,ignore_index=True)



KeyError: 'position'