In [1]:
import Generate as gen

In [2]:
import ConvertTimeSeries as conv

In [3]:
import numpy as np
import pandas as pd

In [4]:
s = gen.System()

In [5]:
data = s.generate(x=[20.,30.],v=[0.4,-0.6])

New planet
            position   t
0  [20.0, 30.0, 0.0]  22


In [6]:
astr = conv.AstroData()

In [7]:
series = astr.convert(data)

In [8]:
x = data['position'].values

In [12]:
# convert an array of values into a dataset matrix
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back-1):
        a = dataset[i:(i+look_back), 0]
        dataX.append(a)
        dataY.append(dataset[i + look_back, 0])
    return numpy.array(dataX), numpy.array(dataY)

In [12]:
import numpy
import matplotlib.pyplot as plt
import pandas
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

Using TensorFlow backend.


In [15]:
data['position'].values

array([array([ 20.39978665,  29.39967998,   0.        ]),
       array([ 20.79935071,  28.79903915,   0.        ]),
       array([ 21.19868279,  28.19807713,   0.        ]),
       array([ 21.59777344,  27.59679398,   0.        ]),
       array([ 21.99661317,  26.9951902 ,   0.        ]),
       array([ 22.39519243,  26.39326675,   0.        ]),
       array([ 22.79350169,  25.79102511,   0.        ]),
       array([ 23.19153147,  25.18846724,   0.        ]),
       array([ 23.58927235,  24.58559559,   0.        ]),
       array([ 23.98671505,  23.98241316,   0.        ]),
       array([ 24.38385042,  23.37892346,   0.        ]),
       array([ 24.78066952,  22.77513052,   0.        ]),
       array([ 25.17716363,  22.1710389 ,   0.        ]),
       array([ 25.57332433,  21.56665367,   0.        ]),
       array([ 25.96914348,  20.96198041,   0.        ]),
       array([ 26.36461332,  20.35702519,   0.        ]),
       array([ 26.75972646,  19.75179455,   0.        ]),
       array([

In [14]:
look_back = 1
x, y = create_dataset(data['position'].values, look_back)

IndexError: too many indices for array

In [17]:
model = Sequential()
model.add(LSTM(4, input_shape=(3, depth)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x, trainY, epochs=100, batch_size=1, verbose=2)

NameError: name 'look_back' is not defined